normV <- function(x) sum(abs(x))
NoInfErr<-function(Response,MU){
MeanR=mean(Response)
Nb=length(Response)
sum0=0
for (k in 1:Nb){
Resp=matrix(Response[k],Nb,1)
MeanR=matrix(mean(Response),Nb,1)
sum0=sum0+normV(Resp-MeanR-MU)
}
return(sum0/Nb^2)
}
library(matrixcalc)
myLARS<-function(DaTa,Type=c("lasso","lars"),NumberIter=0){
Data=DaTa
Predictors=Data[,2:dim(Data)[2]]
NbPredictors=dim(Data)[2]-1
NbPat=dim(Data)[1]
Beta=matrix(0,NbPredictors,1)
NbSteps=min(NbPredictors,NbPat-1)
if(NumberIter>0){
NbSteps=min(NbSteps,NumberIter)}
ActiveSets=matrix(0,NbSteps,1)
ActiveSets0=matrix(0,NbSteps,1)
mu=matrix(mean(Data[,1]),NbPat,1)
CompSet=1:{NbPredictors}
betas=vector("list")
tis=c(0)
AppErr=c()
NoInfErr=c()
Response=as.vector(Data[,1])
MeanR=matrix(mean(Response),NbPat,1)
betas[[1]]=Beta
AppErr=c(AppErr,normV(Response-MeanR-Predictors%*%Beta)/NbPat)
NoInfErr=c(NoInfErr,NoInfErr(Response,Predictors%*%Beta))
if (Type=="lasso"){
Iter=0
Iter2=1
AllSets=c()
jtild=0
comp=0
Check=TRUE
while(Iter<NbSteps && Check){
Iter2=Iter2+1
ytild=Data[,1]-mu
if(jtild==0){
if(comp==1){
CompSet=CompSet[which(CompSet!=Jtild)]
comp=0
}
Iter=Iter+1
correl=apply(Predictors[,CompSet],2,function (xx){
return(abs(t(xx)%*%ytild))})
ActiveSets[Iter]=CompSet[which(correl==max(correl))]
AllSets=c(AllSets,ActiveSets[Iter])
as=ActiveSets[1:Iter][which(ActiveSets[1:Iter]!=0)]
}else{
AllSets=c(AllSets,-as[jtild])
ActiveSets=c(ActiveSets[which(ActiveSets!=as[jtild])],0)
as=ActiveSets[1:Iter]
jtild=0
comp=1}
if(length(as)>1){
DesignM=apply(Predictors[,as],2,function (xx){
return(sign(t(xx)%*%ytild)*xx)
})}else{
DesignM=sign(t(Predictors[,as])%*%ytild)*Predictors[,as]
}
ck=t(Predictors)%*%ytild
Chat=max(abs(t(DesignM)%*%ytild))
if(!{rcond(t(DesignM)%*%DesignM)< 1e-08}){
a=t(Predictors)%*%DesignM%*%solve(t(DesignM)%*%DesignM)%*%matrix(1,length(as),1)
for (k in 1:length(as)){
CompSet=CompSet[which(CompSet!=as[k])]
}
set=matrix(0,2*length(CompSet),1)
i=1
for(index in CompSet){
set[i]=(Chat-ck[index])/(1-a[index])
set[i+1]=(Chat+ck[index])/(1+a[index])
i=i+2
}
c=min(set[which(set>0)])
u=DesignM%*%(solve(t(DesignM)%*%DesignM))%*%matrix(1,length(as),1)
b=c*(solve(t(DesignM)%*%DesignM))%*%matrix(1,length(as),1)
btild=solve(t(DesignM)%*%DesignM)%*%matrix(1,length(as),1)
d=matrix(0,NbPredictors,1)
cj=matrix(0,length(as),1)
for(ind in 1:length(as)){
d[as[ind]]=btild[ind]
cj[ind]=-Beta[as[ind]]/d[as[ind]]
}
cjpos=which(cj>1e-8)
cjmin=Inf
if(length(cjpos)>0){
cjmin=min(cj[cjpos])
}
if(cjmin<c){
mu=mu+cjmin*u
b=cjmin*(solve(t(DesignM)%*%DesignM))%*%matrix(1,length(as),1)
Beta[as]=Beta[as]+cjmin*btild[1:length(as)]
Beta2=Beta
Beta2[as]=sign(t(Predictors[,as])%*%ytild)*Beta2[as]
tis=c(tis,sum(abs(Beta2)))
betas[[Iter2]]=Beta2
AppErr=c(AppErr,normV(Response-MeanR-Predictors%*%Beta2)/NbPat)
NoInfErr=c(NoInfErr,NoInfErr(Response,Predictors%*%Beta2))
jtild=which(cj==cjmin)
Jtild=as[jtild]
Iter=Iter-1
}else{
Beta[as]=Beta[as]+b[1:length(as)]
Beta2=Beta
Beta2[as]=sign(t(Predictors[,as])%*%ytild)*Beta2[as]
tis=c(tis,sum(abs(Beta2)))
betas[[Iter2]]=Beta2
AppErr=c(AppErr,normV(Response-MeanR-Predictors%*%Beta2)/NbPat)
NoInfErr=c(NoInfErr,NoInfErr(Response,Predictors%*%Beta2))
mu=mu+c*u
}
CompSet=1:{NbPredictors}
for (k in 1:length(as)){
CompSet=CompSet[which(CompSet!=as[k])]
}
if(Iter==NbSteps){
Beta=sign(t(Predictors[,as])%*%ytild)*solve(t(DesignM)%*%DesignM)%*%t(DesignM)%*%(Data[,1]-matrix(mean(Data[,1]),NbPat,1))
Beta2=matrix(0,NbPredictors,1)
for(i in 1:length(as)){
Beta2[as[i]]=Beta[i]
}
betas[[Iter2]]=Beta2
}
}else{Check=FALSE}
}
}
object=list(Betas=betas,Ts=tis,AppErrs=AppErr,NoInfErrs=NoInfErr)
class(object)="MyLars"
object
}